import { Language } from "./types";

export const TRANSLATIONS = {
  [Language.EN]: {
    welcome: "Welcome to MySihat Mind",
    tagline: "Your early-intervention mental health companion.",
    getStarted: "Get Started",
    consentTitle: "Informed Consent",
    consentBody: "I understand that my de-identified data will be used for mental health research and NGO referral purposes. I am not being diagnosed, and this is not a replacement for professional therapy.",
    agree: "I Agree",
    selectLang: "Select Language",
    next: "Next",
    back: "Back",
    submit: "Submit",
    screeningTitle: "How have you been feeling?",
    screeningDesc: "Over the last 2 weeks, how often have you been bothered by any of the following problems?",
    phq9: [
      "Little interest or pleasure in doing things",
      "Feeling down, depressed, or hopeless",
      "Trouble falling or staying asleep, or sleeping too much",
      "Feeling tired or having little energy",
      "Poor appetite or overeating",
      "Feeling bad about yourself — or that you are a failure or have let yourself or your family down",
      "Trouble concentrating on things, such as reading the newspaper or watching television",
      "Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual",
      "Thoughts that you would be better off dead or of hurting yourself in some way"
    ],
    gad7: [
      "Feeling nervous, anxious or on edge",
      "Not being able to stop or control worrying",
      "Worrying too much about different things",
      "Trouble relaxing",
      "Being so restless that it is hard to sit still",
      "Becoming easily annoyed or irritable",
      "Feeling afraid as if something awful might happen"
    ],
    options: ["Not at all", "Several days", "More than half the days", "Nearly every day"],
    crisisMsg: "We hear you. You are not alone. Please call Befrienders (03-76272929) or Talian Kasih (15999) now.",
    lowMsg: "Your score indicates low distress. We recommend our 21-day micro-intervention program to maintain your wellbeing.",
    modMsg: "Your score indicates moderate distress. Consider our micro-intervention program and speaking with a counselor.",
    highMsg: "Your score indicates high distress. We strongly recommend reaching out to a professional.",
    referralTitle: "Professional Support",
    programTitle: "21-Day Journey",
    day: "Day",
    exercise: "Exercise",
    reflection: "Reflection",
    breathing: "Breathing",
    completeDay: "Complete Day",
    streak: "Day Streak",
    stats: "Community Impact",
    hello: "Hello",
    howAreYou: "How are you today?",
    settings: "Settings",
    aiModelConfig: "AI Model Configuration",
    chooseModel: "Choose the OpenRouter model for your AI assistant.",
    customModelId: "Custom Model ID",
    supportInfo: "Support & Info",
    revisitOnboarding: "Revisit Onboarding Guide",
    languagePreference: "Language Preference",
    aiSupport: "AI Support Chat",
    chatPlaceholder: "I'm here to listen. How are you feeling?",
    typeMessage: "Type your message...",
    journal: "Journal",
    yourReflections: "Your Reflections",
    getProfessionalHelp: "Get Professional Help",
    moodDepressionAssessment: "Mood & Depression Assessment",
    anxietyStressAssessment: "Anxiety & Stress Assessment",
    startAssessment: "Start Assessment",
    journeyComplete: "Journey Complete",
    loadStats: "Load Stats",
    totalUsers: "Total Users",
    crisisAlerts: "Crisis Alerts",
    severityDistribution: "Severity Distribution",
    low: "Low",
    moderate: "Moderate",
    high: "High",
    crisis: "Crisis",
    assessmentResult: "Assessment Result",
    distress: "Distress",
    callBefrienders: "Call Befrienders",
    findLocalSupport: "Find Local Support",
    startProgram: "Start 21-Day Program",
    backToHome: "Back to Home",
    noReflections: "No reflections yet. Complete a day to start your journal.",
    profileTitle: "Tell us a bit about you",
    stateLabel: "State",
    selectState: "Select State",
    ageRangeLabel: "Age Range",
    selectAge: "Select Age",
    talkToAssistant: "Talk to MySihat Mind assistant",
    days: "Days",
    reflectionPlaceholder: "Type your thoughts here...",
    aiDisclaimer: "AI can make mistakes. Seek professional help if in crisis.",
    breathingTitle: "4-7-8 Breathing",
    cycle: "Cycle",
    inhale: "Inhale",
    hold: "Hold",
    exhale: "Exhale",
    ready: "Ready?",
    pause: "Pause",
    errorOccurred: "An error occurred. Please try again.",
    startBreathing: "Start Breathing",
    breathingGuide: "Inhale (4s) • Hold (7s) • Exhale (8s)",
    programContent: {
      1: { exercise: "Take 5 deep breaths, focusing on the air entering and leaving your body.", reflection: "How did your body feel after the breathing exercise?" },
      2: { exercise: "Write down three things you are grateful for today.", reflection: "What was the best thing that happened today?" },
      3: { exercise: "Take a 10-minute walk and focus on the sensation of your feet hitting the ground.", reflection: "What did you notice during your walk that you usually miss?" }
    },
    whatItIs: "What it is",
    whatItIsNot: "What it is NOT",
    privacyNotice: "Privacy Notice",
    states: {
      "Johor": "Johor",
      "Kedah": "Kedah",
      "Kelantan": "Kelantan",
      "Melaka": "Melaka",
      "Negeri Sembilan": "Negeri Sembilan",
      "Pahang": "Pahang",
      "Perak": "Perak",
      "Perlis": "Perlis",
      "Pulau Pinang": "Pulau Pinang",
      "Sabah": "Sabah",
      "Sarawak": "Sarawak",
      "Selangor": "Selangor",
      "Terengganu": "Terengganu",
      "Kuala Lumpur": "Kuala Lumpur",
      "Labuan": "Labuan",
      "Putrajaya": "Putrajaya",
      "National": "National",
      "Online": "Online"
    },
    onboarding: {
      title: "Welcome to MySihat Mind",
      whatIs: "MySihat Mind is an early-intervention mental health companion designed to help you track your mood, practice mindfulness, and find support.",
      whatIsNot: "This app is NOT a clinical tool. It does not provide medical diagnosis, prescriptions, or replace professional therapy.",
      privacy: "Your privacy matters. All your screening answers and journal entries are stored locally on this device and are not accessible to anyone else.",
      revisit: "You can revisit this guide anytime from the Settings menu."
    }
  },
  [Language.BM]: {
    welcome: "Selamat Datang ke MySihat Mind",
    tagline: "Teman kesihatan mental intervensi awal anda.",
    getStarted: "Mulakan",
    consentTitle: "Keizinan Termaklum",
    consentBody: "Saya faham bahawa data tanpa identiti saya akan digunakan untuk tujuan penyelidikan kesihatan mental dan rujukan NGO. Saya tidak didiagnosis, dan ini bukan pengganti terapi profesional.",
    agree: "Saya Setuju",
    selectLang: "Pilih Bahasa",
    next: "Seterusnya",
    back: "Kembali",
    submit: "Hantar",
    screeningTitle: "Bagaimana perasaan anda?",
    screeningDesc: "Sepanjang 2 minggu yang lalu, berapa kerap anda terganggu oleh masalah berikut?",
    phq9: [
      "Kurang minat atau keseronokan dalam melakukan perkara",
      "Merasa sedih, murung, atau putus asa",
      "Masalah tidur atau terlalu banyak tidur",
      "Merasa letih atau kurang tenaga",
      "Kurang selera makan atau makan berlebihan",
      "Merasa buruk tentang diri sendiri — atau anda seorang yang gagal",
      "Masalah menumpukan perhatian",
      "Bergerak atau bercakap terlalu perlahan atau terlalu gelisah",
      "Fikiran bahawa anda lebih baik mati atau mencederakan diri sendiri"
    ],
    gad7: [
      "Merasa gementar, cemas atau gelisah",
      "Tidak dapat berhenti atau mengawal kebimbangan",
      "Terlalu bimbang tentang pelbagai perkara",
      "Masalah untuk berehat",
      "Sangat gelisah sehingga sukar untuk duduk diam",
      "Menjadi mudah marah atau jengkel",
      "Merasa takut seolah-olah sesuatu yang buruk akan berlaku"
    ],
    options: ["Tidak pernah", "Beberapa hari", "Lebih separuh hari", "Hampir setiap hari"],
    crisisMsg: "Kami mendengar anda. Anda tidak bersendirian. Sila hubungi Befrienders (03-76272929) atau Talian Kasih (15999) sekarang.",
    lowMsg: "Skor anda menunjukkan tahap tekanan yang rendah. Kami mengesyorkan program intervensi mikro 21 hari kami.",
    modMsg: "Skor anda menunjukkan tahap tekanan sederhana. Pertimbangkan program kami dan bercakap dengan kaunselor.",
    highMsg: "Skor anda menunjukkan tahap tekanan yang tinggi. Kami sangat mengesyorkan anda menghubungi profesional.",
    referralTitle: "Sokongan Profesional",
    programTitle: "Perjalanan 21 Hari",
    day: "Hari",
    exercise: "Latihan",
    reflection: "Refleksi",
    breathing: "Pernafasan",
    completeDay: "Selesai Hari Ini",
    streak: "Rentetan Hari",
    stats: "Impak Komuniti",
    hello: "Helo",
    howAreYou: "Apa khabar anda hari ini?",
    settings: "Tetapan",
    aiModelConfig: "Konfigurasi Model AI",
    chooseModel: "Pilih model OpenRouter untuk pembantu AI anda.",
    customModelId: "ID Model Tersuai",
    supportInfo: "Sokongan & Maklumat",
    revisitOnboarding: "Semak Semula Panduan Onboarding",
    languagePreference: "Pilihan Bahasa",
    aiSupport: "Sembang Sokongan AI",
    chatPlaceholder: "Saya di sini untuk mendengar. Bagaimana perasaan anda?",
    typeMessage: "Taip mesej anda...",
    journal: "Jurnal",
    yourReflections: "Refleksi Anda",
    getProfessionalHelp: "Dapatkan Bantuan Profesional",
    moodDepressionAssessment: "Penilaian Mood & Kemurungan",
    anxietyStressAssessment: "Penilaian Kebimbangan & Tekanan",
    startAssessment: "Mulakan Penilaian",
    journeyComplete: "Perjalanan Selesai",
    loadStats: "Muat Turun Statistik",
    totalUsers: "Jumlah Pengguna",
    crisisAlerts: "Amaran Krisis",
    severityDistribution: "Taburan Tahap Keseriusan",
    low: "Rendah",
    moderate: "Sederhana",
    high: "Tinggi",
    crisis: "Krisis",
    assessmentResult: "Keputusan Penilaian",
    distress: "Tekanan",
    callBefrienders: "Hubungi Befrienders",
    findLocalSupport: "Cari Sokongan Tempatan",
    startProgram: "Mulakan Program 21 Hari",
    backToHome: "Kembali ke Laman Utama",
    noReflections: "Belum ada refleksi. Selesaikan satu hari untuk memulakan jurnal anda.",
    profileTitle: "Beritahu kami sedikit tentang anda",
    stateLabel: "Negeri",
    selectState: "Pilih Negeri",
    ageRangeLabel: "Lingkungan Umur",
    selectAge: "Pilih Umur",
    talkToAssistant: "Bercakap dengan pembantu MySihat Mind",
    days: "Hari",
    reflectionPlaceholder: "Taip fikiran anda di sini...",
    aiDisclaimer: "AI boleh membuat kesilapan. Dapatkan bantuan profesional jika dalam krisis.",
    breathingTitle: "Pernafasan 4-7-8",
    cycle: "Kitaran",
    inhale: "Tarik Nafas",
    hold: "Tahan",
    exhale: "Hembus",
    ready: "Sedia?",
    pause: "Jeda",
    errorOccurred: "Ralat telah berlaku. Sila cuba lagi.",
    startBreathing: "Mula Bernafas",
    breathingGuide: "Tarik (4s) • Tahan (7s) • Hembus (8s)",
    programContent: {
      1: { exercise: "Tarik 5 nafas dalam, fokus pada udara yang masuk dan keluar dari badan anda.", reflection: "Bagaimana perasaan badan anda selepas senaman pernafasan?" },
      2: { exercise: "Tuliskan tiga perkara yang anda syukuri hari ini.", reflection: "Apakah perkara terbaik yang berlaku hari ini?" },
      3: { exercise: "Berjalan selama 10 minit dan fokus pada sensasi kaki anda menyentuh tanah.", reflection: "Apa yang anda perasan semasa berjalan yang biasanya anda terlepas pandang?" }
    },
    whatItIs: "Apa itu",
    whatItIsNot: "Apa yang BUKAN",
    privacyNotice: "Notis Privasi",
    states: {
      "Johor": "Johor",
      "Kedah": "Kedah",
      "Kelantan": "Kelantan",
      "Melaka": "Melaka",
      "Negeri Sembilan": "Negeri Sembilan",
      "Pahang": "Pahang",
      "Perak": "Perak",
      "Perlis": "Perlis",
      "Pulau Pinang": "Pulau Pinang",
      "Sabah": "Sabah",
      "Sarawak": "Sarawak",
      "Selangor": "Selangor",
      "Terengganu": "Terengganu",
      "Kuala Lumpur": "Kuala Lumpur",
      "Labuan": "Labuan",
      "Putrajaya": "Putrajaya",
      "National": "National",
      "Online": "Online"
    },
    onboarding: {
      title: "Selamat Datang ke MySihat Mind",
      whatIs: "MySihat Mind adalah teman kesihatan mental intervensi awal yang direka untuk membantu anda menjejaki mood, mengamalkan kesedaran, dan mencari sokongan.",
      whatIsNot: "Aplikasi ini BUKAN alat klinikal. Ia tidak menyediakan diagnosis perubatan, preskripsi, atau menggantikan terapi profesional.",
      privacy: "Privasi anda penting. Semua jawapan saringan dan entri jurnal anda disimpan secara tempatan pada peranti ini dan tidak boleh diakses oleh orang lain.",
      revisit: "Anda boleh menyemak semula panduan ini pada bila-bila masa dari menu Tetapan."
    }
  },
  [Language.ZH]: {
    welcome: "欢迎来到 MySihat Mind",
    tagline: "您的心理健康早期干预伙伴。",
    getStarted: "开始使用",
    consentTitle: "知情同意",
    consentBody: "我明白我的去标识化数据将用于心理健康研究和非政府组织转介目的。我没有被诊断，这不能替代专业治疗。",
    agree: "我同意",
    selectLang: "选择语言",
    next: "下一步",
    back: "返回",
    submit: "提交",
    screeningTitle: "你最近感觉如何？",
    screeningDesc: "在过去的两周里，你有多经常受到以下任何问题的困扰？",
    phq9: [
      "对做事失去兴趣或乐趣",
      "感到情绪低落、抑郁或绝望",
      "入睡困难、易醒或睡眠过多",
      "感到疲倦或精力不足",
      "食欲不振或暴饮暴食",
      "觉得自己很糟，或者觉得自己很失败",
      "注意力难以集中",
      "动作或言语缓慢，或者坐立不安",
      "产生自残或自杀的念头"
    ],
    gad7: [
      "感到紧张、焦虑或急躁",
      "无法停止或控制忧虑",
      "对各种不同的事情忧虑过多",
      "难以放松",
      "由于不安而无法静坐",
      "变得容易烦恼或急躁",
      "感到害怕，好像有什么可怕的事会发生"
    ],
    options: ["完全没有", "有几天", "一半以上的时间", "几乎每天"],
    crisisMsg: "我们听到你的声音。你并不孤单。请立即致电 Befrienders (03-76272929) 或 Talian Kasih (15999)。",
    lowMsg: "你的得分显示压力较低。我们建议你参加我们的21天微干预计划以保持健康。",
    modMsg: "你的得分显示中度压力。考虑参加我们的计划并咨询心理咨询师。",
    highMsg: "你的得分显示高度压力。我们强烈建议你寻求专业人士的帮助。",
    referralTitle: "专业支持",
    programTitle: "21天旅程",
    day: "天",
    exercise: "练习",
    reflection: "反思",
    breathing: "呼吸",
    completeDay: "完成今日任务",
    streak: "连续天数",
    stats: "社区影响",
    hello: "你好",
    howAreYou: "你今天感觉如何？",
    settings: "设置",
    aiModelConfig: "AI 模型配置",
    chooseModel: "为您的 AI 助手选择 OpenRouter 模型。",
    customModelId: "自定义模型 ID",
    supportInfo: "支持与信息",
    revisitOnboarding: "重新查看入门指南",
    languagePreference: "语言偏好",
    aiSupport: "AI 支持聊天",
    chatPlaceholder: "我在这里倾听。你感觉如何？",
    typeMessage: "输入您的信息...",
    journal: "日记",
    yourReflections: "您的反思",
    getProfessionalHelp: "寻求专业帮助",
    moodDepressionAssessment: "情绪与抑郁评估",
    anxietyStressAssessment: "焦虑与压力评估",
    startAssessment: "开始评估",
    journeyComplete: "旅程完成",
    loadStats: "加载统计数据",
    totalUsers: "总用户数",
    crisisAlerts: "危机警报",
    severityDistribution: "严重程度分布",
    low: "低",
    moderate: "中度",
    high: "高",
    crisis: "危机",
    assessmentResult: "评估结果",
    distress: "压力",
    callBefrienders: "致电 Befrienders",
    findLocalSupport: "寻找当地支持",
    startProgram: "开始 21 天计划",
    backToHome: "返回首页",
    noReflections: "还没有反思。完成一天的任务来开始您的日记。",
    profileTitle: "请告诉我们一些关于您的信息",
    stateLabel: "州属",
    selectState: "选择州属",
    ageRangeLabel: "年龄范围",
    selectAge: "选择年龄",
    talkToAssistant: "与 MySihat Mind 助手交谈",
    days: "天",
    reflectionPlaceholder: "在这里输入您的想法...",
    aiDisclaimer: "AI 可能会犯错。如果处于危机中，请寻求专业帮助。",
    breathingTitle: "4-7-8 呼吸法",
    cycle: "循环",
    inhale: "吸气",
    hold: "屏息",
    exhale: "呼气",
    ready: "准备好了吗？",
    pause: "暂停",
    errorOccurred: "发生错误。请再试一次。",
    startBreathing: "开始呼吸",
    breathingGuide: "吸气 (4秒) • 屏息 (7秒) • 呼气 (8秒)",
    programContent: {
      1: { exercise: "深呼吸 5 次，专注于空气进入和离开身体的感觉。", reflection: "呼吸练习后你的身体感觉如何？" },
      2: { exercise: "写下今天你感激的三件事。", reflection: "今天发生的最棒的事情是什么？" },
      3: { exercise: "散步 10 分钟，专注于脚底接触地面的感觉。", reflection: "在散步过程中，你注意到了哪些平时会忽略的事情？" }
    },
    whatItIs: "它是什么",
    whatItIsNot: "它不是什么",
    privacyNotice: "隐私声明",
    states: {
      "Johor": "柔佛",
      "Kedah": "吉打",
      "Kelantan": "吉兰丹",
      "Melaka": "马六甲",
      "Negeri Sembilan": "森美兰",
      "Pahang": "彭亨",
      "Perak": "霹雳",
      "Perlis": "玻璃市",
      "Pulau Pinang": "槟城",
      "Sabah": "沙巴",
      "Sarawak": "砂拉越",
      "Selangor": "雪兰莪",
      "Terengganu": "登嘉楼",
      "Kuala Lumpur": "吉隆坡",
      "Labuan": "纳闽",
      "Putrajaya": "布城",
      "National": "全国",
      "Online": "线上"
    },
    onboarding: {
      title: "欢迎来到 MySihat Mind",
      whatIs: "MySihat Mind 是一个早期干预心理健康伙伴，旨在帮助您追踪情绪、练习正念并寻求支持。",
      whatIsNot: "此应用程序不是临床工具。它不提供医疗诊断、处方，也不替代专业治疗。",
      privacy: "您的隐私至关重要。您的所有筛查答案和日记条目都存储在此设备本地，其他人无法访问。",
      revisit: "您可以随时从“设置”菜单重新查看此指南。"
    }
  },
  [Language.TA]: {
    welcome: "MySihat Mind-க்கு வரவேற்கிறோம்",
    tagline: "உங்கள் ஆரம்பக்கால மனநலத் துணையாக.",
    getStarted: "தொடங்கவும்",
    consentTitle: "தகவல் ஒப்புதல்",
    consentBody: "எனது அடையாளம் நீக்கப்பட்ட தரவு மனநல ஆராய்ச்சி மற்றும் NGO பரிந்துரை நோக்கங்களுக்காகப் பயன்படுத்தப்படும் என்பதை நான் புரிந்துகொள்கிறேன். எனக்கு நோய் கண்டறியப்படவில்லை, இது தொழில்முறை சிகிச்சைக்கு மாற்றாகாது.",
    agree: "நான் ஒப்புக்கொள்கிறேன்",
    selectLang: "மொழியைத் தேர்ந்தெடுக்கவும்",
    next: "அடுத்து",
    back: "பின்னால்",
    submit: "சமர்ப்பிக்கவும்",
    screeningTitle: "நீங்கள் எப்படி உணருகிறீர்கள்?",
    screeningDesc: "கடந்த 2 வாரங்களில், பின்வரும் பிரச்சனைகளால் நீங்கள் எவ்வளவு அடிக்கடி பாதிக்கப்பட்டுள்ளீர்கள்?",
    phq9: [
      "காரியங்களைச் செய்வதில் ஆர்வம் அல்லது மகிழ்ச்சி குறைவு",
      "மனச்சோர்வு, அல்லது நம்பிக்கையற்ற உணர்வு",
      "தூங்குவதில் சிரமம் அல்லது அதிக தூக்கம்",
      "சோர்வு அல்லது குறைந்த ஆற்றல்",
      "பசியின்மை அல்லது அதிகப்படியான உணவு",
      "உங்களைப் பற்றி மோசமாக உணருதல் - அல்லது நீங்கள் ஒரு தோல்வி",
      "விஷயங்களில் கவனம் செலுத்துவதில் சிரமம்",
      "மிக மெதுவாகப் பேசுதல் அல்லது நகருதல் அல்லது மிகவும் அமைதியற்ற நிலை",
      "இறக்க வேண்டும் அல்லது உங்களை நீங்களே காயப்படுத்திக் கொள்ள வேண்டும் என்ற எண்ணங்கள்"
    ],
    gad7: [
      "பதட்டமாக, கவலையாக அல்லது விளிம்பில் உணருதல்",
      "கவலையை நிறுத்தவோ அல்லது கட்டுப்படுத்தவோ முடியாமல் போதல்",
      "வெவ்வேறு விஷயங்களைப் பற்றி அதிகம் கவலைப்படுதல்",
      "ஓய்வெடுப்பதில் சிரமம்",
      "அமைதியற்ற நிலையில் இருத்தல்",
      "எளிதில் எரிச்சலடைதல்",
      "ஏதோ மோசமான ஒன்று நடக்கப்போவது போன்ற பயம்"
    ],
    options: ["இல்லவே இல்லை", "சில நாட்கள்", "பாதிக்கும் மேற்பட்ட நாட்கள்", "கிட்டத்தட்ட ஒவ்வொரு நாளும்"],
    crisisMsg: "உங்களை நாங்கள் கேட்கிறோம். நீங்கள் தனியாக இல்லை. தயவுசெய்து இப்பொழுதே Befrienders (03-76272929) அல்லது Talian Kasih (15999) ஐ அழைக்கவும்.",
    lowMsg: "உங்கள் மதிப்பெண் குறைந்த மன அழுத்தத்தைக் காட்டுகிறது. உங்கள் நல்வாழ்வைப் பராமரிக்க எங்களின் 21 நாள் திட்டத்தைப் பரிந்துரைக்கிறோம்.",
    modMsg: "உங்கள் மதிப்பெண் மிதமான மன அழுத்தத்தைக் காட்டுகிறது. எங்கள் திட்டத்தைப் பரிசீலித்து ஆலோசகரிடம் பேசவும்.",
    highMsg: "உங்கள் மதிப்பெண் அதிக மன அழுத்தத்தைக் காட்டுகிறது. தொழில்முறை உதவியை நாடுமாறு நாங்கள் கடுமையாகப் பரிந்துரைக்கிறோம்.",
    referralTitle: "தொழில்முறை ஆதரவு",
    programTitle: "21 நாள் பயணம்",
    day: "நாள்",
    exercise: "பயிற்சி",
    reflection: "பிரதிபலிப்பு",
    breathing: "சுவாசம்",
    completeDay: "இன்றைய நாளை முடிக்கவும்",
    streak: "நாள் தொடர்ச்சி",
    stats: "சமூக தாக்கம்",
    hello: "வணக்கம்",
    howAreYou: "இன்று நீங்கள் எப்படி இருக்கிறீர்கள்?",
    settings: "அமைப்புகள்",
    aiModelConfig: "AI மாடல் கட்டமைப்பு",
    chooseModel: "உங்கள் AI உதவியாளருக்கான OpenRouter மாடலைத் தேர்ந்தெடுக்கவும்.",
    customModelId: "தனிப்பயன் மாடல் ID",
    supportInfo: "ஆதரவு மற்றும் தகவல்",
    revisitOnboarding: "ஆன்போர்டிங் வழிகாட்டியை மீண்டும் பார்க்கவும்",
    languagePreference: "மொழி விருப்பம்",
    aiSupport: "AI ஆதரவு அரட்டை",
    chatPlaceholder: "நான் கேட்க இங்கே இருக்கிறேன். நீங்கள் எப்படி உணருகிறீர்கள்?",
    typeMessage: "உங்கள் செய்தியைத் தட்டச்சு செய்யவும்...",
    journal: "ஜர்னல்",
    yourReflections: "உங்கள் பிரதிபலிப்புகள்",
    getProfessionalHelp: "தொழில்முறை உதவியைப் பெறுங்கள்",
    moodDepressionAssessment: "மனநிலை மற்றும் மனச்சோர்வு மதிப்பீடு",
    anxietyStressAssessment: "கவலை மற்றும் மன அழுத்த மதிப்பீடு",
    startAssessment: "மதிப்பீட்டைத் தொடங்கவும்",
    journeyComplete: "பயணம் முடிந்தது",
    loadStats: "புள்ளிவிவரங்களை ஏற்றவும்",
    totalUsers: "மொத்த பயனர்கள்",
    crisisAlerts: "நெருக்கடி எச்சரிக்கைகள்",
    severityDistribution: "தீவிரத்தன்மை விநியோகம்",
    low: "குறைவு",
    moderate: "மிதமானது",
    high: "அதிகம்",
    crisis: "நெருக்கடி",
    assessmentResult: "மதிப்பீட்டு முடிவு",
    distress: "மன அழுத்தம்",
    callBefrienders: "Befrienders ஐ அழைக்கவும்",
    findLocalSupport: "உள்ளூர் ஆதரவைக் கண்டறியவும்",
    startProgram: "21 நாள் திட்டத்தைத் தொடங்கவும்",
    backToHome: "முகப்புப் பக்கத்திற்குச் செல்லவும்",
    noReflections: "இன்னும் பிரதிபலிப்புகள் இல்லை. உங்கள் ஜர்னலைத் தொடங்க ஒரு நாளை முடிக்கவும்.",
    profileTitle: "உங்களைப் பற்றி கொஞ்சம் சொல்லுங்கள்",
    stateLabel: "மாநிலம்",
    selectState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    ageRangeLabel: "வயது வரம்பு",
    selectAge: "வயதைத் தேர்ந்தெடுக்கவும்",
    talkToAssistant: "MySihat Mind உதவியாளருடன் பேசுங்கள்",
    days: "நாட்கள்",
    reflectionPlaceholder: "உங்கள் எண்ணங்களை இங்கே தட்டச்சு செய்யவும்...",
    aiDisclaimer: "AI தவறுகளைச் செய்யலாம். நெருக்கடியில் இருந்தால் தொழில்முறை உதவியை நாடுங்கள்.",
    breathingTitle: "4-7-8 சுவாசம்",
    cycle: "சுழற்சி",
    inhale: "உள்ளிழுக்கவும்",
    hold: "பிடிக்கவும்",
    exhale: "வெளியிடவும்",
    ready: "தயாரா?",
    pause: "நிறுத்து",
    errorOccurred: "ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    startBreathing: "சுவாசத்தைத் தொடங்குங்கள்",
    breathingGuide: "உள்ளிழுக்கவும் (4வி) • பிடிக்கவும் (7வி) • வெளியிடவும் (8வி)",
    programContent: {
      1: { exercise: "5 முறை ஆழமாக சுவாசிக்கவும், உங்கள் உடலுக்குள் காற்று செல்வதையும் வெளியேறுவதையும் கவனிக்கவும்.", reflection: "சுவாசப் பயிற்சிக்குப் பிறகு உங்கள் உடல் எப்படி உணர்ந்தது?" },
      2: { exercise: "இன்று நீங்கள் நன்றியுடன் இருக்கும் மூன்று விஷயங்களை எழுதுங்கள்.", reflection: "இன்று நடந்த மிகச் சிறந்த விஷயம் எது?" },
      3: { exercise: "10 நிமிடம் நடைப்பயிற்சி மேற்கொள்ளுங்கள், உங்கள் கால்கள் தரையில் படும் உணர்வில் கவனம் செலுத்துங்கள்.", reflection: "உங்கள் நடைப்பயிற்சியின் போது நீங்கள் வழக்கமாகத் தவறவிடும் எதைக் கவனித்தீர்கள்?" }
    },
    whatItIs: "அது என்ன",
    whatItIsNot: "அது என்ன அல்ல",
    privacyNotice: "தனியுரிமை அறிவிப்பு",
    states: {
      "Johor": "ஜோகூர்",
      "Kedah": "கெடா",
      "Kelantan": "கிளாந்தான்",
      "Melaka": "மலாக்கா",
      "Negeri Sembilan": "நெகிரி செம்பிலான்",
      "Pahang": "பகாங்",
      "Perak": "பேராக்",
      "Perlis": "பெர்லிஸ்",
      "Pulau Pinang": "பினாங்கு",
      "Sabah": "சபா",
      "Sarawak": "சரவாக்",
      "Selangor": "சிலாங்கூர்",
      "Terengganu": "திரங்கானு",
      "Kuala Lumpur": "கோலாலம்பூர்",
      "Labuan": "லாபுவான்",
      "Putrajaya": "புத்ராஜெயா",
      "National": "தேசிய",
      "Online": "ஆன்லைன்"
    },
    onboarding: {
      title: "MySihat Mind-க்கு வரவேற்கிறோம்",
      whatIs: "MySihat Mind என்பது உங்கள் மனநிலையைக் கண்காணிக்கவும், நினைவாற்றலைப் பயிற்சி செய்யவும் மற்றும் ஆதரவைக் கண்டறியவும் உதவும் வகையில் வடிவமைக்கப்பட்ட ஒரு ஆரம்பக்கால மனநலத் துணையாகும்.",
      whatIsNot: "இந்த ஆப் ஒரு மருத்துவக் கருவி அல்ல. இது மருத்துவ நோயறிதல், மருந்துச் சீட்டுகளை வழங்காது அல்லது தொழில்முறை சிகிச்சைக்கு மாற்றாகாது.",
      privacy: "உங்கள் தனியுரிமை முக்கியமானது. உங்களின் அனைத்து ஸ்கிரீனிங் பதில்களும் ஜர்னல் உள்ளீடுகளும் இந்தச் சாதனத்தில் உள்ளூர் சேமிப்பகத்தில் சேமிக்கப்படும், மற்றவர்கள் அணுக முடியாது.",
      revisit: "அமைப்புகள் மெனுவிலிருந்து எந்த நேரத்திலும் இந்த வழிகாட்டியை மீண்டும் பார்க்கலாம்."
    }
  }
};
